### ISSUE TITLE
yay installation ==> ERROR: Running makepkg as root is not allowed as it can cause permanent, catastrophic damage to your system.

### ISSUE THREAD

**Issue by RashiqAzhan** [astos/astos#12]
I can't seem to install yay to a snapshot since `makepkg` dropped support for elevated permission execution. I'm trying to install yay and would like some guidance on how to get about it.

I've tried chroot-ing into the desired snapshot and here is the output.
```
==> ERROR: Running makepkg as root is not allowed as it can cause permanent, catastrophic damage to your system
```

Directly trying to install fails with a `read-only system` error.

**Comment by i2** [comment]
Thank you! This is a good issue to report.

I think I am getting to the source of this issue. In the meantime, this might be a work-around:
1. Create a user while chrooted: `useradd -m -G wheel tempuser`
2. In chroot, `su tempuser`
3. Install yay or any other AUR helper

Please report back here.

**Comment by RashiqAzhan** [comment]
I am positive I cd-ed to yay-bin. I can see the `PKGBUILD` when I `ls`.

To be explicit. The `home` dir has `username` and a `tempuser` folder. I first tried inside the `username` folder and got the above result.

Trying inside the `tempuser` asks me for a password. I tried my admin password and without any password but it did not work resulting in this output.
```
==> WARNING: Failed to install built package(s).
```

**Comment by CuBeRJAN** [comment]
To install AUR packages you'd have to chroot in as your user ```sudo ast run <snapshot> su <user>```
Then you can install stuff and once done leave chroot with ```exit```

**Comment by i2** [comment]
I'd say it's worth adding this tip to the readme file.

**Comment by CuBeRJAN** [comment]
> I get this after step 2.
> 
> ```bash
> ==> ERROR: You do not have write permission for the directory $BUILDDIR (/home/username/yay-bin).
>     Aborting . . .
> ```
> This is the result after running `makepkg -si` as per the [docs](https://github.com/Jguer/yay#binary).

Appears you don't have the ownership of the directory, try ```sudo chown -R <user> /home/<user>```

**Comment by RashiqAzhan** [comment]
Running `sudo ast run username su username` and then git cloning yay worked. I was using `sudo ast chroot` cd-ing to `home` folder and then cloning yay which meant `root` was the owner of the file instead of `username` or `tempuser`. Many thanks to @CuBeRJAN and @i2 for the assist.
