### ISSUE TITLE
remove gnome-extra from the gnome profile

### ISSUE THREAD

**Issue by luke876** [astos/astos#34]
I think it is safe to say that the first post-install step of 90% of users will be `ast remove 1 gnome-extra`. All the gnome games and unmaintained tools should not be installed by default.

**Comment by CuBeRJAN** [comment]
Good point, both the Plasma and Gnome desktops were slimmed down.
https://github.com/astos/astos/commit/fecc8df8f6dc33e545d1baa9e290574e3546f264
