### ISSUE TITLE
Last booted deployment is the same as the current deployment

### ISSUE THREAD

**Issue by luke876** [astos/astos#36]
Since it is possible to edit (and break) the deployed snapshot, ast should not let the last booted and current deployment be the same one.

**Comment by CuBeRJAN** [comment]
it's actually not the same snapshot, it only has the same number
if you're booted into snapshot 3 and update it and deploy, when you then use last booted deployment you are booting the old version of snapshot 3, before the update

**Comment by CuBeRJAN** [comment]
maybe we should make it a bit clearer, it can be a but confusing this way

**Comment by luke876** [comment]
I see, that makes sense but it is a bit confusing that the current and last deployments have the same name in the boot menu.
If I actually broke the new deployment I would probably still select that entry and find out it is a backup though.
