### ISSUE TITLE
clone entire tree?

### ISSUE THREAD

**Issue by xankz** [astos/astos#37]
is there a way to clone entire trees instead of single snapshots for backup when installing packages? or is there a way to swap snapshots so if something goes wrong when updating the parent tree, i can swap it in-place with the clone backup?

**Comment by i2** [comment]
1. This is not currently implemented, but it is a good idea!
2. This is theoretically possible, but it might have bad consequences for child nodes/snapshots if a parent and corrupt child node are swapped.

**Comment by CuBeRJAN** [comment]
Well, it's implemented now! To clone an entire tree use 'ast clone-tree' and then the number of the snapshot to clone recursively
